apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-go-file-reader
  namespace: default
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: standard-csi-expandable
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
