apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-go-file-reader
  namespace: default
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
